export const ACTION_TYPES = {
  PICK_PLAYER: "PICK_PLAYER",
  REMOVE_PLAYER: "REMOVE_PLAYER",
  SET_PLAYERS: "SET_PLAYERS",
  SET_TRACKED_TEAM: "SET_TRACKED_TEAM",
  UNDO_PICK_PLAYER: "UNDO_PICK_PLAYER"
};
