export const ACTION_TYPES = {
  INCREMENT_DRAFT: "INCREMENT_DRAFT",
  PICK_PLAYER: "PICK_PLAYER",
  REMOVE_PLAYER: "REMOVE_PLAYER",
  RESET_DRAFT: "RESET_DRAFT",
  SELECT_PLAYER: "SELECT_PLAYER",
  SET_ACTIVE_TEAM: "SET_ACTIVE_TEAM",
  SET_NUMBER_OF_TEAMS: "SET_NUMBER_OF_TEAMS",
  SET_PLAYERS: "SET_PLAYERS",
  SET_ROSTER_FORMAT: "SET_ROSTER_FORMAT",
  SET_TRACKED_TEAM: "SET_TRACKED_TEAM",
  TOGGLE_PPR: "TOGGLE_PPR",
  TOGGLE_ROSTER_FORMATTING: "TOGGLE_ROSTER_FORMATTING",
  UNDO_PICK_PLAYER: "UNDO_PICK_PLAYER"
};
