---
title: "linear"
author: "jjtimmons"
date: "7/21/2018"
fig_width: 5 
fig_height: 5
---

# Linear forecasting with the plm package

Testing a model for predicting player FF points per season using linear regressions of panel data

## QB

```{r}
library(plm)
library(pryr)

setwd("~/Documents/GitHub/ff/analysis")

qb.data <- player.data[["QB"]]
qb.formula <- formula(fantpt ~ lag(fantpt) + age)
qb.model <- plm(qb.formula, data = qb.data, index = c("name","year"), model="pooling")
summary(qb.model)

# for each player in the data set
qb.coors = data.frame(x=numeric(0), y=numeric(0))
med.pts <- median(qb.data$fantpt, na.rm = TRUE)
for (name in unique(qb.data$name)) {
  player <- qb.data[qb.data$name == name, ]
  
  for (i in 1:nrow(player)) {
    # if there's no data on player last year, skip
    if (i-1 < 1) next
    
    lag1 <- player[i-1, "fantpt"]
  
    player.now <- player[i,]
    
    qb.coors <- rbind(
       qb.coors,
       list(
          x = sum(c(1, lag1, player.now$age) * qb.model$coefficients, na.rm = TRUE),
          y = player[i+1,"fantpt"]
       )
    )
  }
}

# only keep the cases where we know next season's score
qb.coors <- qb.coors[complete.cases(qb.coors),]

# calculate R-squared
total <- with(qb.coors, sum((y - mean(y))^2))
var <- with(qb.coors, sum((y - x)^2))
qb.rsqrd <- round(1 - (var / total), digits = 3)
qb.rsqrd <- paste0("R^2 = ", qb.rsqrd)
qb.rsqrd


```

## RB

```{r}
library(plm)
library(pryr)

setwd("~/Documents/GitHub/ff/analysis")

rb.data <- player.data[["RB"]]
rb.formula <- formula(fantpt ~ lag(fantpt, 1:2) + age)
rb.model <- plm(rb.formula, data = rb.data, index = c("name","year"), model="pooling")
summary(rb.model)

# for each player in the data set
rb.coors = data.frame(x=numeric(0), y=numeric(0))
med.pts <- median(rb.data$fantpt, na.rm = TRUE)
for (name in unique(rb.data$name)) {
  player <- rb.data[rb.data$name == name, ]
  
  for (i in 1:nrow(player)) {
    # there's no last year data to compare model against
    if (i-2 < 1) next
    
    lag1 <- player[i-1, "fantpt"]
    lag2 <- player[i-2, "fantpt"]
    lag1.yds <- player[i-1, "yds.1"]
    
    rb.coors <- rbind(
       rb.coors,
       list(
          x = sum(c(1, lag1, lag2, player.now$age) * rb.model$coefficients, na.rm = TRUE),
          y = player[i+1,"fantpt"]
       )
    )
  }
}

# only keep the cases where we know next season's score
rb.coors <- rb.coors[complete.cases(rb.coors),]

# calculate R-squared
total <- with(rb.coors, sum((y - mean(y))^2))
var <- with(rb.coors, sum((y - x)^2))
rb.rsqrd <- round(1 - (var / total), digits = 3)
rb.rsqrd <- paste0("R^2 = ", rb.rsqrd)
rb.rsqrd

rb.plot

```

## WR

```{r}
library(plm)
library(pryr)

setwd("~/Documents/GitHub/ff/analysis")

wr.data <- player.data[["WR"]]
wr.formula <- formula(fantpt ~ lag(fantpt, 1) + age)
wr.model <- plm(wr.formula, data = wr.data, index = c("name","year"), model="pooling")
summary(wr.model)

# for each player in the data set
wr.coors = data.frame(x=numeric(0), y=numeric(0))
med.pts <- median(wr.data$fantpt, na.rm = TRUE)
for (name in unique(wr.data$name)) {
  player <- wr.data[wr.data$name == name, ]
  
  for (i in 1:nrow(player)) {
    # there's no last year data to compare model against
    if (i-1 < 1) next
    
    lag1 <- player[i-1, "fantpt"]
    player.now <- player[i,]
    
    wr.coors <- rbind(
       wr.coors,
       list(
          x = sum(c(1, lag1, player.now$age) * wr.model$coefficients, na.rm = TRUE),
          y = player[i+1,"fantpt"]
       )
    )
  }
}

# only keep the cases where we know next season's score
wr.coors <- wr.coors[complete.cases(wr.coors),]

# calculate R-squared: 0.3035777
total <- with(wr.coors, sum((y - mean(y))^2))
var <- with(wr.coors, sum((y - x)^2))
wr.rsqrd <- round(1 - (var / total), digits = 3)
wr.rsqrd <- paste0("R^2 = ", wr.rsqrd)
wr.rsqrd

wr.plot

```


## TE

```{r}
library(plm)
library(pryr)

setwd("~/Documents/GitHub/ff/analysis")

te.data <- player.data[["TE"]]
te.formula <- formula(fantpt ~ lag(fantpt, 1:2))
te.model <- plm(te.formula, data = te.data, index = c("name","year"), model="pooling")
summary(te.model)

# for each player in the data set
te.coors = data.frame(x=numeric(0), y=numeric(0))
med.pts <- median(te.data$fantpt, na.rm = TRUE)
for (name in unique(te.data$name)) {
  player <- te.data[te.data$name == name, ]
  
  for (i in 1:nrow(player)) {
    # there's no last year data to compare model against
    if (i-2 < 1) next
    
    player.now <- player[i,]
    
    lag1 <- player[i-1, "fantpt"]
    lag2 <- player[i-2, "fantpt"]
    
    te.coors <- rbind(
       te.coors,
       list(
          x = sum(c(1, lag1, lag2) * te.model$coefficients, na.rm = TRUE),
          y = player[i+1,"fantpt"]
       )
    )
  }
}

# only keep the cases where we know next season's score
te.coors <- te.coors[complete.cases(te.coors),]

# calculate R-squared
total <- with(te.coors, sum((y - mean(y))^2))
var <- with(te.coors, sum((y - x)^2))
te.rsqrd <- round(1 - (var / total), digits = 3)
te.rsqrd <- paste0("R^2 = ", te.rsqrd)
te.rsqrd

```

## Plots

```{r}
qb.plot %<a-% {
  plot(qb.coors$x, qb.coors$y,
     cex = 0.8,
     xlim = c(0, 350),
     ylim = c(0, 450),
     ann=FALSE)
  abline(0, 1, col = 'red', lty = 'dashed', lwd = 2)
  text(70, 420, labels = qb.rsqrd)
  title(main = "QB", line = 0.5)
  title(xlab = "estimate", ylab = "actual", line = 2.25)
}

rb.plot %<a-% {
  plot(rb.coors$x, rb.coors$y,
     cex = 0.8,
     xlim = c(0, 280),
     ylim = c(0, 330),
     ann=FALSE)
  abline(0, 1, col = 'red', lty = 'dashed', lwd = 2)
  text(45, 305, labels = rb.rsqrd)
  title(main = "RB", line = 0.5)
  title(xlab = "estimate", ylab = "actual", line = 2.25)
}

wr.plot %<a-% {
  plot(wr.coors$x, wr.coors$y,
     cex = 0.8,
     xlim = c(0, 200),
     ylim = c(0, 280),
     ann=FALSE)
  abline(0, 1, col = 'red', lty = 'dashed', lwd = 2)
  text(35, 260, labels = wr.rsqrd)
  title(main = "WR", line = 0.5)
  title(xlab = "estimate", ylab = "actual", line = 2.25)
}

te.plot %<a-% {
  plot(te.coors$x, te.coors$y,
     cex = 0.8,
     xlim = c(0, 150),
     ylim = c(0, 200),
     ann=FALSE)
  abline(0, 1, col = 'red', lty = 'dashed', lwd = 2)
  text(25, 185, labels = te.rsqrd)
  title(main = "TE", line = 0.5)
  title(xlab = "estimate", ylab = "actual", line = 2.25)
}

all.plot %<a-% {
  par(mfrow=c(2,2), mar=c(3.5, 3.5, 2, 0.5))
  qb.plot
  rb.plot
  wr.plot
  te.plot
}

```