---
title: "linear"
author: "jjtimmons"
date: "7/21/2018"
fig_width: 5 
fig_height: 5
---

# Linear forecasting with the plm package

Testing a model for predicting player FF points per season using linear regressions of panel data

## QB

```{r}
library(plm)

setwd("~/Documents/GitHub/ff/analysis")

qb.data <- player.data[["QB"]]
qb.formula <- formula(fantpt ~ lag(fantpt, 1:3) + age)
qb.model <- plm(qb.formula, data = qb.data, index = c("name","year"), model="pooling")
summary(qb.model)

# for each player in the data set
coors = data.frame(x=numeric(0), y=numeric(0))
med.pts <- median(qb.data$fantpt, na.rm = TRUE)
for (name in unique(qb.data$name)) {
  player <- qb.data[qb.data$name == name, ]
  
  for (i in 1:nrow(player)) {
    # there's no last year data to compare model against
    # if (!isTRUE(player[i-1, "fantpt"] > 0)) next
    
    # there's no next year data to compare model against
    if (!isTRUE(player[i+1,"fantpt"] > 0)) next
    
    # if there's no data on player last year, average for players age
    player.now <- player[i,]
    
    lag1 <- ifelse(i-1>0, player[i-1, "fantpt"], med.pts)
    lag2 <- ifelse(i-2>0, player[i-2, "fantpt"], med.pts)
    lag3 <- ifelse(i-3>0, player[i-3, "fantpt"], med.pts)
    lag4 <- ifelse(i-4>0, player[i-4, "fantpt"], med.pts)
    
    coors <- rbind(
       coors,
       list(
          x = sum(c(1, lag1, lag2, lag3, player.now$age) * qb.model$coefficients, na.rm = TRUE),
          y = player[i+1,"fantpt"]
       )
    )
  }
}

# calculate R-squared: 0.3035777
total <- with(coors, sum((y - mean(y))^2))
var <- with(coors, sum((y - x)^2))
print(1 - (var / total))

plot(coors$x, coors$y,
     xlab = "estimated",
     ylab = "actual",
     main = "QB Fantasy Points Prediction",
     xlim = c(0, 450),
     ylim = c(0, 400))
abline(0, 1, col = 'red', lty = 'dashed', lwd = 2)

```

## RB

```{r}
library(plm)

setwd("~/Documents/GitHub/ff/analysis")

rb.data <- player.data[["RB"]]
rb.formula <- formula(fantpt ~ lag(fantpt, 1:3) + age)
rb.model <- plm(rb.formula, data = rb.data, index = c("name","year"), model="pooling")
summary(rb.model)

# for each player in the data set
coors = data.frame(x=numeric(0), y=numeric(0))
med.pts <- median(rb.data$fantpt, na.rm = TRUE)
for (name in unique(rb.data$name)) {
  player <- rb.data[rb.data$name == name, ]
  
  for (i in 1:nrow(player)) {
    # there's no last year data to compare model against
    # if (!isTRUE(player[i-1, "fantpt"] > 0)) next
    
    # there's no next year data to compare model against
    if (!isTRUE(player[i+1,"fantpt"] > 0)) next
    
    # if there's no data on player last year, average for players age
    player.now <- player[i,]
    
    lag1 <- ifelse(i-1>0, player[i-1, "fantpt"], med.pts)
    lag2 <- ifelse(i-2>0, player[i-2, "fantpt"], med.pts)
    lag3 <- ifelse(i-3>0, player[i-3, "fantpt"], med.pts)
    lag4 <- ifelse(i-4>0, player[i-4, "fantpt"], med.pts)
    
    coors <- rbind(
       coors,
       list(
          x = sum(c(1, lag1, lag2, lag3, player.now$age) * full.model$coefficients, na.rm = TRUE),
          y = player[i+1,"fantpt"]
       )
    )
  }
}

# calculate R-squared: 0.3035777
total <- with(coors, sum((y - mean(y))^2))
var <- with(coors, sum((y - x)^2))
print(1 - (var / total))

plot(coors$x, coors$y,
     xlab = "estimated",
     ylab = "actual",
     main = "RB Fantasy Points Prediction",
     xlim = c(15, 220),
     ylim = c(0, 280))
abline(0, 1, col = 'red', lty = 'dashed', lwd = 2)

```

## WR

```{r}
library(plm)

setwd("~/Documents/GitHub/ff/analysis")

wr.data <- player.data[["WR"]]
wr.formula <- formula(fantpt ~ lag(fantpt, 1:3) + lag(tgt) + age)
wr.model <- plm(wr.formula, data = wr.data, index = c("name","year"), model="pooling")
summary(wr.model)

# for each player in the data set
coors = data.frame(x=numeric(0), y=numeric(0))
med.pts <- median(wr.data$fantpt, na.rm = TRUE)
for (name in unique(wr.data$name)) {
  player <- wr.data[wr.data$name == name, ]
  
  for (i in 1:nrow(player)) {
    # there's no last year data to compare model against
    # if (!isTRUE(player[i-1, "fantpt"] > 0)) next
    
    # there's no next year data to compare model against
    if (!isTRUE(player[i+1,"fantpt"] > 0)) next
    
    # if there's no data on player last year, average for players age
    player.now <- player[i,]
    
    lag1 <- ifelse(i-1>0, player[i-1, "fantpt"], med.pts)
    lag2 <- ifelse(i-2>0, player[i-2, "fantpt"], med.pts)
    lag3 <- ifelse(i-3>0, player[i-3, "fantpt"], med.pts)
    lag4 <- ifelse(i-4>0, player[i-4, "fantpt"], med.pts)
    
    coors <- rbind(
       coors,
       list(
          x = sum(c(1, lag1, lag2, lag3, player.now$age) * qb.model$coefficients, na.rm = TRUE),
          y = player[i+1,"fantpt"]
       )
    )
  }
}

# calculate R-squared: 0.3035777
total <- with(coors, sum((y - mean(y))^2))
var <- with(coors, sum((y - x)^2))
print(1 - (var / total))

plot(coors$x, coors$y,
     xlab = "estimated",
     ylab = "actual",
     main = "WR Fantasy Points Prediction",
     xlim = c(5, 240),
     ylim = c(0, 250))
abline(0, 1, col = 'red', lty = 'dashed', lwd = 2)

```
